export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as PostsDisplay} from './PostsDisplay'
export {default as RegistrationForm} from './RegistrationForm'
export {default as PostForm} from './PostForm'